<?php

declare(strict_types=1);

// @generated by bin/generate-constants-stub.php
// phpcs:ignoreFile -- Arquivo auxiliar para autocompletar constantes no IDE.

if (!defined('ACC_MANAGER')) {
    define('ACC_MANAGER', 1);
}

if (!defined('ACC_TAG')) {
    define('ACC_TAG', 'Minha Conta');
}

if (!defined('ADMIN_DESC')) {
    define('ADMIN_DESC', 'Sistema de gerenciamento de conteúdo e marketing digital da Zen Agência Web.');
}

if (!defined('ADMIN_MAINTENANCE')) {
    define('ADMIN_MAINTENANCE', 0);
}

if (!defined('ADMIN_MODE')) {
    define('ADMIN_MODE', 1);
}

if (!defined('ADMIN_NAME')) {
    define('ADMIN_NAME', 'ZENCONTROL');
}

if (!defined('ADMIN_VERSION')) {
    define('ADMIN_VERSION', '3.5.0');
}

if (!defined('ADMIN_WC_CUSTOM')) {
    define('ADMIN_WC_CUSTOM', 1);
}

if (!defined('AGENCY_ADDR')) {
    define('AGENCY_ADDR', 'Rua Antonio Corsetti, 221 - Sala 1');
}

if (!defined('AGENCY_CITY')) {
    define('AGENCY_CITY', 'Caxias do Sul');
}

if (!defined('AGENCY_CONTACT')) {
    define('AGENCY_CONTACT', 'Marcos Moreira');
}

if (!defined('AGENCY_COUNTRY')) {
    define('AGENCY_COUNTRY', 'BRASIL');
}

if (!defined('AGENCY_EMAIL')) {
    define('AGENCY_EMAIL', 'marcos@zen.ppg.br');
}

if (!defined('AGENCY_NAME')) {
    define('AGENCY_NAME', 'Zen Agência Web');
}

if (!defined('AGENCY_PHONE')) {
    define('AGENCY_PHONE', '(54) 3419.9425');
}

if (!defined('AGENCY_SUPPORT')) {
    define('AGENCY_SUPPORT', '(54) 99634.9424');
}

if (!defined('AGENCY_UF')) {
    define('AGENCY_UF', 'RS');
}

if (!defined('AGENCY_URL')) {
    define('AGENCY_URL', 'https://zen.ppg.br');
}

if (!defined('AGENCY_ZIP')) {
    define('AGENCY_ZIP', '95084-220');
}

if (!defined('APP_ALBUMS')) {
    define('APP_ALBUMS', 0);
}

if (!defined('APP_CERTIFICATIONS')) {
    define('APP_CERTIFICATIONS', 0);
}

if (!defined('APP_COMMENTS')) {
    define('APP_COMMENTS', 1);
}

if (!defined('APP_CTAS')) {
    define('APP_CTAS', 1);
}

if (!defined('APP_CURIOSITIES')) {
    define('APP_CURIOSITIES', 0);
}

if (!defined('APP_CV')) {
    define('APP_CV', 0);
}

if (!defined('APP_DEBUG')) {
    define('APP_DEBUG', 'true');
}

if (!defined('APP_DEPOSITIONS')) {
    define('APP_DEPOSITIONS', 0);
}

if (!defined('APP_HELLO')) {
    define('APP_HELLO', 0);
}

if (!defined('APP_LANDING_PAGES')) {
    define('APP_LANDING_PAGES', 1);
}

if (!defined('APP_LEADS')) {
    define('APP_LEADS', 1);
}

if (!defined('APP_LINKTREE')) {
    define('APP_LINKTREE', 0);
}

if (!defined('APP_LINK_PAGES')) {
    define('APP_LINK_PAGES', 1);
}

if (!defined('APP_LINK_POSTS')) {
    define('APP_LINK_POSTS', 1);
}

if (!defined('APP_LINK_PRODUCTS')) {
    define('APP_LINK_PRODUCTS', 1);
}

if (!defined('APP_LINK_PROPERTIES')) {
    define('APP_LINK_PROPERTIES', 1);
}

if (!defined('APP_MATERIALS')) {
    define('APP_MATERIALS', 0);
}

if (!defined('APP_OUVIDORIA')) {
    define('APP_OUVIDORIA', 0);
}

if (!defined('APP_PAGES')) {
    define('APP_PAGES', 1);
}

if (!defined('APP_PARTNERS')) {
    define('APP_PARTNERS', 0);
}

if (!defined('APP_PORTFOLIO')) {
    define('APP_PORTFOLIO', 0);
}

if (!defined('APP_POSTS')) {
    define('APP_POSTS', 1);
}

if (!defined('APP_POSTS_AMP')) {
    define('APP_POSTS_AMP', 0);
}

if (!defined('APP_POSTS_INSTANT_ARTICLE')) {
    define('APP_POSTS_INSTANT_ARTICLE', 0);
}

if (!defined('APP_PRODUCTS_DORIPEL')) {
    define('APP_PRODUCTS_DORIPEL', 1);
}

if (!defined('APP_REPRESENTATIVES')) {
    define('APP_REPRESENTATIVES', 0);
}

if (!defined('APP_SEARCH')) {
    define('APP_SEARCH', 1);
}

if (!defined('APP_SLIDE')) {
    define('APP_SLIDE', 1);
}

if (!defined('APP_THANKYOU_PAGES')) {
    define('APP_THANKYOU_PAGES', 1);
}

if (!defined('APP_USERS')) {
    define('APP_USERS', 1);
}

if (!defined('APP_VIDEOS')) {
    define('APP_VIDEOS', 0);
}

if (!defined('AVATAR_H')) {
    define('AVATAR_H', 500);
}

if (!defined('AVATAR_W')) {
    define('AVATAR_W', 500);
}

if (!defined('BASE')) {
    define('BASE', 'https://localhost/doripel');
}

if (!defined('COMMENT_MODERATE')) {
    define('COMMENT_MODERATE', 1);
}

if (!defined('COMMENT_ON_PAGES')) {
    define('COMMENT_ON_PAGES', 1);
}

if (!defined('COMMENT_ON_POSTS')) {
    define('COMMENT_ON_POSTS', 1);
}

if (!defined('COMMENT_ON_PRODUCTS')) {
    define('COMMENT_ON_PRODUCTS', 1);
}

if (!defined('COMMENT_ORDER')) {
    define('COMMENT_ORDER', 'DESC');
}

if (!defined('COMMENT_RESPONSE_ORDER')) {
    define('COMMENT_RESPONSE_ORDER', 'ASC');
}

if (!defined('COMMENT_SEND_EMAIL')) {
    define('COMMENT_SEND_EMAIL', 1);
}

if (!defined('E_PDT_SIZE')) {
    define('E_PDT_SIZE', 'default');
}

if (!defined('DB_ALBUMS')) {
    define('DB_ALBUMS', 'ws_albums');
}

if (!defined('DB_ALBUMS_IMAGE')) {
    define('DB_ALBUMS_IMAGE', 'ws_albums_images');
}

if (!defined('DB_AUTO_PING')) {
    define('DB_AUTO_PING', 1);
}

if (!defined('DB_AUTO_TRASH')) {
    define('DB_AUTO_TRASH', 1);
}

if (!defined('DB_CARD_USER')) {
    define('DB_CARD_USER', 'trv_card_user');
}

if (!defined('DB_CATEGORIES')) {
    define('DB_CATEGORIES', 'ws_posts_categories');
}

if (!defined('DB_CITIES')) {
    define('DB_CITIES', 'cities');
}

if (!defined('DB_COMMENTS')) {
    define('DB_COMMENTS', 'ws_comments');
}

if (!defined('DB_COMMENTS_LIKES')) {
    define('DB_COMMENTS_LIKES', 'ws_comments_likes');
}

if (!defined('DB_ORDERS_ITEMS')) {
    define('DB_ORDERS_ITEMS', 'ws_orders_items');
}

if (!defined('DB_CONF')) {
    define('DB_CONF', 'ws_config');
}

if (!defined('DB_CURIOSITIES')) {
    define('DB_CURIOSITIES', 'ws_curiosities');
}

if (!defined('DB_CV')) {
    define('DB_CV', 'ws_job_candidates');
}

if (!defined('DB_DEPOSITIONS')) {
    define('DB_DEPOSITIONS', 'ws_depositions');
}

if (!defined('DB_HELLO')) {
    define('DB_HELLO', 'ws_hellobar');
}

if (!defined('DB_LANDING_PAGES')) {
    define('DB_LANDING_PAGES', 'ws_landingpages');
}

if (!defined('DB_LANDING_PAGES_IMAGES')) {
    define('DB_LANDING_PAGES_IMAGES', 'ws_landingpages_images');
}

if (!defined('DB_LEADS')) {
    define('DB_LEADS', 'ws_leads');
}

if (!defined('DB_MATCATEGORIES')) {
    define('DB_MATCATEGORIES', 'ws_matcategories');
}

if (!defined('DB_MATERIAIS')) {
    define('DB_MATERIAIS', 'ws_materiais');
}

if (!defined('DB_OUVIDORIA')) {
    define('DB_OUVIDORIA', 'ws_ouvidoria');
}

if (!defined('DB_PAGES')) {
    define('DB_PAGES', 'ws_pages');
}

if (!defined('DB_PAGES_IMAGE')) {
    define('DB_PAGES_IMAGE', 'ws_pages_images');
}

if (!defined('DB_PARTNERS')) {
    define('DB_PARTNERS', 'ws_partners');
}

if (!defined('DB_PDT_BRANDS_DORIPEL')) {
    define('DB_PDT_BRANDS_DORIPEL', 'ws_products_brands_doripel');
}

if (!defined('DB_PDT_CATS_DORIPEL')) {
    define('DB_PDT_CATS_DORIPEL', 'ws_products_categories_doripel');
}

if (!defined('DB_PDT_COLORS_DORIPEL')) {
    define('DB_PDT_COLORS_DORIPEL', 'ws_products_colors_doripel');
}

if (!defined('DB_PDT_DORIPEL')) {
    define('DB_PDT_DORIPEL', 'ws_products_doripel');
}

if (!defined('DB_PDT_GALLERY_DORIPEL')) {
    define('DB_PDT_GALLERY_DORIPEL', 'ws_products_gallery_doripel');
}

if (!defined('DB_PDT_IMAGE_CAT_DORIPEL')) {
    define('DB_PDT_IMAGE_CAT_DORIPEL', 'ws_products_images_cat_doripel');
}

if (!defined('DB_PDT_IMAGE_DORIPEL')) {
    define('DB_PDT_IMAGE_DORIPEL', 'ws_products_images_doripel');
}

if (!defined('DB_PDT_STOCK_DORIPEL')) {
    define('DB_PDT_STOCK_DORIPEL', 'ws_products_stock_doripel');
}

if (!defined('DB_PORTFOLIO')) {
    define('DB_PORTFOLIO', 'portfolio');
}

if (!defined('DB_PORTFOLIO_CATEGORIES')) {
    define('DB_PORTFOLIO_CATEGORIES', 'portfolio_categories');
}

if (!defined('DB_POSTS')) {
    define('DB_POSTS', 'ws_posts');
}

if (!defined('DB_POSTS_IMAGE')) {
    define('DB_POSTS_IMAGE', 'ws_posts_images');
}

if (!defined('DB_REPRESENTATIVES')) {
    define('DB_REPRESENTATIVES', 'ws_representatives');
}

if (!defined('DB_SEARCH')) {
    define('DB_SEARCH', 'ws_search');
}

if (!defined('DB_SLIDES')) {
    define('DB_SLIDES', 'ws_slides');
}

if (!defined('DB_STATES')) {
    define('DB_STATES', 'states');
}

if (!defined('DB_THANKYOU_PAGES')) {
    define('DB_THANKYOU_PAGES', 'ws_thankyoupages');
}

if (!defined('DB_USERS')) {
    define('DB_USERS', 'ws_users');
}

if (!defined('DB_USERS_ADDR')) {
    define('DB_USERS_ADDR', 'ws_users_address');
}

if (!defined('DB_USERS_NOTES')) {
    define('DB_USERS_NOTES', 'ws_users_notes');
}

if (!defined('DB_VIEWS_ONLINE')) {
    define('DB_VIEWS_ONLINE', 'ws_siteviews_online');
}

if (!defined('DB_VIEWS_VIEWS')) {
    define('DB_VIEWS_VIEWS', 'ws_siteviews_views');
}

if (!defined('DB_WC_API')) {
    define('DB_WC_API', 'workcontrol_api');
}

if (!defined('DB_WC_CODE')) {
    define('DB_WC_CODE', 'workcontrol_code');
}

if (!defined('DB_YOUTUBE')) {
    define('DB_YOUTUBE', 'ws_youtube');
}

if (!defined('IMAGE_H')) {
    define('IMAGE_H', 628);
}

if (!defined('IMAGE_W')) {
    define('IMAGE_W', 1200);
}

if (!defined('INCLUDE_PATH')) {
    define('INCLUDE_PATH', 'https://localhost/doripel/themes/doripel');
}

if (!defined('LEVEL_WC_ALBUMS')) {
    define('LEVEL_WC_ALBUMS', 9);
}

if (!defined('LEVEL_WC_CERTIFICATIONS')) {
    define('LEVEL_WC_CERTIFICATIONS', 9);
}

if (!defined('LEVEL_WC_COMMENTS')) {
    define('LEVEL_WC_COMMENTS', 6);
}

if (!defined('LEVEL_WC_CONFIG_API')) {
    define('LEVEL_WC_CONFIG_API', 10);
}

if (!defined('LEVEL_WC_CONFIG_CODES')) {
    define('LEVEL_WC_CONFIG_CODES', 10);
}

if (!defined('LEVEL_WC_CONFIG_MASTER')) {
    define('LEVEL_WC_CONFIG_MASTER', 10);
}

if (!defined('LEVEL_WC_CTAS')) {
    define('LEVEL_WC_CTAS', 6);
}

if (!defined('LEVEL_WC_CURIOSITIES')) {
    define('LEVEL_WC_CURIOSITIES', 9);
}

if (!defined('LEVEL_WC_CV')) {
    define('LEVEL_WC_CV', 9);
}

if (!defined('LEVEL_WC_DEPOSITIONS')) {
    define('LEVEL_WC_DEPOSITIONS', 9);
}

if (!defined('LEVEL_WC_HELLO')) {
    define('LEVEL_WC_HELLO', 9);
}

if (!defined('LEVEL_WC_LANDING_PAGES')) {
    define('LEVEL_WC_LANDING_PAGES', 9);
}

if (!defined('LEVEL_WC_LEADS')) {
    define('LEVEL_WC_LEADS', 9);
}

if (!defined('LEVEL_WC_LINKTREE')) {
    define('LEVEL_WC_LINKTREE', 6);
}

if (!defined('LEVEL_WC_OUVIDORIA')) {
    define('LEVEL_WC_OUVIDORIA', 9);
}

if (!defined('LEVEL_WC_PAGES')) {
    define('LEVEL_WC_PAGES', 9);
}

if (!defined('LEVEL_WC_PARTNERS')) {
    define('LEVEL_WC_PARTNERS', 9);
}

if (!defined('LEVEL_WC_PORTFOLIO')) {
    define('LEVEL_WC_PORTFOLIO', 6);
}

if (!defined('LEVEL_WC_POSTS')) {
    define('LEVEL_WC_POSTS', 6);
}

if (!defined('LEVEL_WC_PRODUCTS_DORIPEL')) {
    define('LEVEL_WC_PRODUCTS_DORIPEL', 9);
}

if (!defined('LEVEL_WC_REPORTS')) {
    define('LEVEL_WC_REPORTS', 9);
}

if (!defined('LEVEL_WC_REPRESENTATIVES')) {
    define('LEVEL_WC_REPRESENTATIVES', 9);
}

if (!defined('LEVEL_WC_SEGMENTS')) {
    define('LEVEL_WC_SEGMENTS', 9);
}

if (!defined('LEVEL_WC_SERVICES')) {
    define('LEVEL_WC_SERVICES', 9);
}

if (!defined('LEVEL_WC_SLIDES')) {
    define('LEVEL_WC_SLIDES', 9);
}

if (!defined('LEVEL_WC_THANKYOU_PAGES')) {
    define('LEVEL_WC_THANKYOU_PAGES', 9);
}

if (!defined('LEVEL_WC_USERS')) {
    define('LEVEL_WC_USERS', 9);
}

if (!defined('LEVEL_WC_VIDEOS')) {
    define('LEVEL_WC_VIDEOS', 9);
}

if (!defined('MAIL_HOST')) {
    define('MAIL_HOST', 'mail.seu-dominio.com.br');
}

if (!defined('MAIL_MODE')) {
    define('MAIL_MODE', 'ssl');
}

if (!defined('MAIL_PASS')) {
    define('MAIL_PASS', 'senha-do-email');
}

if (!defined('MAIL_PORT')) {
    define('MAIL_PORT', '465');
}

if (!defined('MAIL_SENDER')) {
    define('MAIL_SENDER', 'Doripel Móveis');
}

if (!defined('MAIL_SMTP')) {
    define('MAIL_SMTP', 'doripel@doripel.com.br');
}

if (!defined('MAIL_TESTER')) {
    define('MAIL_TESTER', 'marcosleaomoreira@gmail.com');
}

if (!defined('MAIL_USER')) {
    define('MAIL_USER', 'doripel@doripel.com.br');
}

if (!defined('REQUIRE_PATH')) {
    define('REQUIRE_PATH', 'themes/doripel');
}

if (!defined('SEGMENT_FB_PAGE_ID')) {
    define('SEGMENT_FB_PAGE_ID', '');
}

if (!defined('SEGMENT_FB_PIXEL_ID')) {
    define('SEGMENT_FB_PIXEL_ID', '');
}

if (!defined('SEGMENT_GL_ADWORDS_ID')) {
    define('SEGMENT_GL_ADWORDS_ID', '');
}

if (!defined('SEGMENT_GL_ADWORDS_LABEL')) {
    define('SEGMENT_GL_ADWORDS_LABEL', '');
}

if (!defined('SEGMENT_GL_ANALYTICS')) {
    define('SEGMENT_GL_ANALYTICS', 'G-R5E6VNDD81');
}

if (!defined('SEGMENT_GL_TAGMANAGER')) {
    define('SEGMENT_GL_TAGMANAGER', '');
}

if (!defined('SEGMENT_WC_BLOG')) {
    define('SEGMENT_WC_BLOG', 1);
}

if (!defined('SEGMENT_WC_USER')) {
    define('SEGMENT_WC_USER', 1);
}

if (!defined('SIS_CACHE_TIME')) {
    define('SIS_CACHE_TIME', 10);
}

if (!defined('SIS_CONFIG_WC')) {
    define('SIS_CONFIG_WC', 1);
}

if (!defined('SIS_DB_HOST')) {
    define('SIS_DB_HOST', 'localhost');
}

if (!defined('SIS_DB_NAME')) {
    define('SIS_DB_NAME', 'uwdoripel_website');
}

if (!defined('SIS_DB_PASS')) {
    define('SIS_DB_PASS', 'gs2Ju000~');
}

if (!defined('SIS_DB_USER')) {
    define('SIS_DB_USER', 'uwdoripel_website');
}

if (!defined('SITE_ADDR_ADDR')) {
    define('SITE_ADDR_ADDR', 'Av. Julio Vanzin, 1600 - Área Industrial');
}

if (!defined('SITE_ADDR_CITY')) {
    define('SITE_ADDR_CITY', 'Lagoa Vermelha');
}

if (!defined('SITE_ADDR_CNPJ')) {
    define('SITE_ADDR_CNPJ', '90.608.084/0001-33');
}

if (!defined('SITE_ADDR_COUNTRY')) {
    define('SITE_ADDR_COUNTRY', 'Brasil');
}

if (!defined('SITE_ADDR_DISTRICT')) {
    define('SITE_ADDR_DISTRICT', 'Industrial II');
}

if (!defined('SITE_ADDR_EMAIL')) {
    define('SITE_ADDR_EMAIL', 'doripel@doripel.com.br');
}

if (!defined('SITE_ADDR_IE')) {
    define('SITE_ADDR_IE', 'ISENTO');
}

if (!defined('SITE_ADDR_NAME')) {
    define('SITE_ADDR_NAME', 'Doripel Móveis');
}

if (!defined('SITE_ADDR_PHONE_A')) {
    define('SITE_ADDR_PHONE_A', '(54) 3358-6500');
}

if (!defined('SITE_ADDR_RS')) {
    define('SITE_ADDR_RS', 'MOVEIS DORIPEL LTDA');
}

if (!defined('SITE_ADDR_SITE')) {
    define('SITE_ADDR_SITE', 'zen.ppg.br');
}

if (!defined('SITE_ADDR_UF')) {
    define('SITE_ADDR_UF', 'RS');
}

if (!defined('SITE_ADDR_WHATS')) {
    define('SITE_ADDR_WHATS', '(54) 3358-6500');
}

if (!defined('SITE_ADDR_ZIP')) {
    define('SITE_ADDR_ZIP', '93300-000');
}

if (!defined('SITE_DESC')) {
    define('SITE_DESC', 'Doripel Móveis é uma indústria de móveis especializada em dormitórios das linhas casal, solteiro e infantil. Esta localizada na cidade de Lagoa Vermelha no estado do Rio Grande do Sul.');
}

if (!defined('SITE_FONT_NAME')) {
    define('SITE_FONT_NAME', 'Ubuntu');
}

if (!defined('SITE_FONT_WHIGHT')) {
    define('SITE_FONT_WHIGHT', '300,400,500,700');
}

if (!defined('SITE_NAME')) {
    define('SITE_NAME', 'Doripel');
}

if (!defined('SITE_SOCIAL_FB')) {
    define('SITE_SOCIAL_FB', 1);
}

if (!defined('SITE_SOCIAL_FB_APP')) {
    define('SITE_SOCIAL_FB_APP', '');
}

if (!defined('SITE_SOCIAL_FB_AUTHOR')) {
    define('SITE_SOCIAL_FB_AUTHOR', 'DoripelMoveis');
}

if (!defined('SITE_SOCIAL_FB_DOMAIN_VERIFICATION')) {
    define('SITE_SOCIAL_FB_DOMAIN_VERIFICATION', '');
}

if (!defined('SITE_SOCIAL_FB_PAGE')) {
    define('SITE_SOCIAL_FB_PAGE', 'DoripelMoveis');
}

if (!defined('SITE_SOCIAL_FB_PAGE_ID')) {
    define('SITE_SOCIAL_FB_PAGE_ID', '');
}

if (!defined('SITE_SOCIAL_INSTAGRAM')) {
    define('SITE_SOCIAL_INSTAGRAM', 'moveis.doripel');
}

if (!defined('SITE_SOCIAL_LINKEDIN')) {
    define('SITE_SOCIAL_LINKEDIN', '');
}

if (!defined('SITE_SOCIAL_NAME')) {
    define('SITE_SOCIAL_NAME', 'Doripel Móveis');
}

if (!defined('SITE_SOCIAL_TWITTER')) {
    define('SITE_SOCIAL_TWITTER', '');
}

if (!defined('SITE_SOCIAL_YOUTUBE')) {
    define('SITE_SOCIAL_YOUTUBE', '');
}

if (!defined('SITE_SUBNAME')) {
    define('SITE_SUBNAME', 'Móveis');
}

if (!defined('SLIDE_H')) {
    define('SLIDE_H', 1080);
}

if (!defined('SLIDE_W')) {
    define('SLIDE_W', 1920);
}

if (!defined('THEME')) {
    define('THEME', 'doripel');
}

if (!defined('THUMB_H')) {
    define('THUMB_H', 800);
}

if (!defined('THUMB_W')) {
    define('THUMB_W', 800);
}

if (!defined('VIDEO_H')) {
    define('VIDEO_H', 720);
}

if (!defined('VIDEO_W')) {
    define('VIDEO_W', 1280);
}
